# Generated by Django 4.2.2 on 2023-07-06 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="created_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
