# Generated by Django 3.2.10 on 2023-07-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_discount_my_discount_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={},
        ),
    ]
