# Generated by Django 5.0.6 on 2024-06-24 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_historicaldiscount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(default=1)),
                ("url", models.URLField(blank=True)),
                ("request_data", models.TextField(blank=True)),
                ("response_code", models.CharField(blank=True, max_length=3)),
                ("os", models.CharField(blank=True, max_length=20)),
                ("http_agent", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог пользователя",
                "verbose_name_plural": "Логи пользователей",
            },
        ),
    ]
