# Generated by Django 3.2.10 on 2023-07-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_discount_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='my_discount_status',
        ),
    ]
